Update CI.yml
GridtNetwork/gridt-client pull request #139
Opened 2020-09-08 17:13 UTC by Drvanon

The old branch was no longer in use so for this to be here does not make much sense.

2020-09-08 17:18 UTC, Yori-O92 approved these changes

2020-09-09 15:07 UTC, marickmanrho requested changes

2020-09-09 15:07 UTC, marickmanrho commented on .github/workflows/CI.yml
> +    branches: [ master, api-development ]
This should be changed to development,

2020-09-09 15:13 UTC, Drvanon commented on .github/workflows/CI.yml
> +    branches: [ master, api-development ]
Good call.

2020-09-09 15:35 UTC, marickmanrho approved these changes
Great, ready to merge.

2020-09-09 15:59 UTC, merged